# Generated by Django 5.2.1 on 2025-06-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.CreateModel(
            name='ParserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=50, verbose_name='Артикул товара')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Выполнено без ошибок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.product', verbose_name='Скаченый продукт')),
            ],
            options={
                'verbose_name': 'История парсинга',
                'verbose_name_plural': 'История парсинга',
            },
        ),
    ]
